// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SectranAdminsColumns holds the columns for the "sectran_admins" table.
	SectranAdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SectranAdminsTable holds the schema information for the "sectran_admins" table.
	SectranAdminsTable = &schema.Table{
		Name:       "sectran_admins",
		Columns:    SectranAdminsColumns,
		PrimaryKey: []*schema.Column{SectranAdminsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SectranAdminsTable,
	}
)

func init() {
}
