// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sectran_admin/ent/predicate"
	"sectran_admin/ent/sectranadmin"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectranAdminDelete is the builder for deleting a SectranAdmin entity.
type SectranAdminDelete struct {
	config
	hooks    []Hook
	mutation *SectranAdminMutation
}

// Where appends a list predicates to the SectranAdminDelete builder.
func (sad *SectranAdminDelete) Where(ps ...predicate.SectranAdmin) *SectranAdminDelete {
	sad.mutation.Where(ps...)
	return sad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sad *SectranAdminDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sad.sqlExec, sad.mutation, sad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sad *SectranAdminDelete) ExecX(ctx context.Context) int {
	n, err := sad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sad *SectranAdminDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sectranadmin.Table, sqlgraph.NewFieldSpec(sectranadmin.FieldID, field.TypeInt))
	if ps := sad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sad.mutation.done = true
	return affected, err
}

// SectranAdminDeleteOne is the builder for deleting a single SectranAdmin entity.
type SectranAdminDeleteOne struct {
	sad *SectranAdminDelete
}

// Where appends a list predicates to the SectranAdminDelete builder.
func (sado *SectranAdminDeleteOne) Where(ps ...predicate.SectranAdmin) *SectranAdminDeleteOne {
	sado.sad.mutation.Where(ps...)
	return sado
}

// Exec executes the deletion query.
func (sado *SectranAdminDeleteOne) Exec(ctx context.Context) error {
	n, err := sado.sad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sectranadmin.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sado *SectranAdminDeleteOne) ExecX(ctx context.Context) {
	if err := sado.Exec(ctx); err != nil {
		panic(err)
	}
}
