// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sectran_admin/ent/sectranadmin"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectranAdminCreate is the builder for creating a SectranAdmin entity.
type SectranAdminCreate struct {
	config
	mutation *SectranAdminMutation
	hooks    []Hook
}

// Mutation returns the SectranAdminMutation object of the builder.
func (sac *SectranAdminCreate) Mutation() *SectranAdminMutation {
	return sac.mutation
}

// Save creates the SectranAdmin in the database.
func (sac *SectranAdminCreate) Save(ctx context.Context) (*SectranAdmin, error) {
	return withHooks(ctx, sac.sqlSave, sac.mutation, sac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sac *SectranAdminCreate) SaveX(ctx context.Context) *SectranAdmin {
	v, err := sac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sac *SectranAdminCreate) Exec(ctx context.Context) error {
	_, err := sac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sac *SectranAdminCreate) ExecX(ctx context.Context) {
	if err := sac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sac *SectranAdminCreate) check() error {
	return nil
}

func (sac *SectranAdminCreate) sqlSave(ctx context.Context) (*SectranAdmin, error) {
	if err := sac.check(); err != nil {
		return nil, err
	}
	_node, _spec := sac.createSpec()
	if err := sqlgraph.CreateNode(ctx, sac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sac.mutation.id = &_node.ID
	sac.mutation.done = true
	return _node, nil
}

func (sac *SectranAdminCreate) createSpec() (*SectranAdmin, *sqlgraph.CreateSpec) {
	var (
		_node = &SectranAdmin{config: sac.config}
		_spec = sqlgraph.NewCreateSpec(sectranadmin.Table, sqlgraph.NewFieldSpec(sectranadmin.FieldID, field.TypeInt))
	)
	return _node, _spec
}

// SectranAdminCreateBulk is the builder for creating many SectranAdmin entities in bulk.
type SectranAdminCreateBulk struct {
	config
	err      error
	builders []*SectranAdminCreate
}

// Save creates the SectranAdmin entities in the database.
func (sacb *SectranAdminCreateBulk) Save(ctx context.Context) ([]*SectranAdmin, error) {
	if sacb.err != nil {
		return nil, sacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sacb.builders))
	nodes := make([]*SectranAdmin, len(sacb.builders))
	mutators := make([]Mutator, len(sacb.builders))
	for i := range sacb.builders {
		func(i int, root context.Context) {
			builder := sacb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SectranAdminMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sacb *SectranAdminCreateBulk) SaveX(ctx context.Context) []*SectranAdmin {
	v, err := sacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sacb *SectranAdminCreateBulk) Exec(ctx context.Context) error {
	_, err := sacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sacb *SectranAdminCreateBulk) ExecX(ctx context.Context) {
	if err := sacb.Exec(ctx); err != nil {
		panic(err)
	}
}
