// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilUpdatedAt(value *time.Time) *AccountUpdate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilUpdatedAt(value *time.Time) *AccountUpdateOne {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilUpdatedAt(value *time.Time) *AccountCreate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilUsername(value *string) *AccountUpdate {
	if value != nil {
		return a.SetUsername(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilUsername(value *string) *AccountUpdateOne {
	if value != nil {
		return a.SetUsername(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilUsername(value *string) *AccountCreate {
	if value != nil {
		return a.SetUsername(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilPort(value *uint32) *AccountUpdate {
	if value != nil {
		return a.SetPort(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilPort(value *uint32) *AccountUpdateOne {
	if value != nil {
		return a.SetPort(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilPort(value *uint32) *AccountCreate {
	if value != nil {
		return a.SetPort(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilProtocol(value *uint8) *AccountUpdate {
	if value != nil {
		return a.SetProtocol(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilProtocol(value *uint8) *AccountUpdateOne {
	if value != nil {
		return a.SetProtocol(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilProtocol(value *uint8) *AccountCreate {
	if value != nil {
		return a.SetProtocol(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilPassword(value *string) *AccountUpdate {
	if value != nil {
		return a.SetPassword(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilPassword(value *string) *AccountUpdateOne {
	if value != nil {
		return a.SetPassword(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilPassword(value *string) *AccountCreate {
	if value != nil {
		return a.SetPassword(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilPrivateKey(value *string) *AccountUpdate {
	if value != nil {
		return a.SetPrivateKey(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilPrivateKey(value *string) *AccountUpdateOne {
	if value != nil {
		return a.SetPrivateKey(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilPrivateKey(value *string) *AccountCreate {
	if value != nil {
		return a.SetPrivateKey(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdate) SetNotNilDeviceID(value *uint64) *AccountUpdate {
	if value != nil {
		return a.SetDeviceID(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountUpdateOne) SetNotNilDeviceID(value *uint64) *AccountUpdateOne {
	if value != nil {
		return a.SetDeviceID(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AccountCreate) SetNotNilDeviceID(value *uint64) *AccountCreate {
	if value != nil {
		return a.SetDeviceID(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdate) SetNotNilUpdatedAt(value *time.Time) *DepartmentUpdate {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DepartmentUpdateOne {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentCreate) SetNotNilUpdatedAt(value *time.Time) *DepartmentCreate {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdate) SetNotNilName(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetName(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdateOne) SetNotNilName(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetName(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentCreate) SetNotNilName(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetName(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdate) SetNotNilArea(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetArea(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdateOne) SetNotNilArea(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetArea(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentCreate) SetNotNilArea(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetArea(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdate) SetNotNilDescription(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetDescription(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdateOne) SetNotNilDescription(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetDescription(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentCreate) SetNotNilDescription(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetDescription(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdate) SetNotNilParentDepartmentID(value *uint64) *DepartmentUpdate {
	if value != nil {
		return d.SetParentDepartmentID(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdateOne) SetNotNilParentDepartmentID(value *uint64) *DepartmentUpdateOne {
	if value != nil {
		return d.SetParentDepartmentID(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentCreate) SetNotNilParentDepartmentID(value *uint64) *DepartmentCreate {
	if value != nil {
		return d.SetParentDepartmentID(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdate) SetNotNilParentDepartments(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetParentDepartments(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentUpdateOne) SetNotNilParentDepartments(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetParentDepartments(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DepartmentCreate) SetNotNilParentDepartments(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetParentDepartments(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdate) SetNotNilUpdatedAt(value *time.Time) *DeviceUpdate {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DeviceUpdateOne {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceCreate) SetNotNilUpdatedAt(value *time.Time) *DeviceCreate {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdate) SetNotNilName(value *string) *DeviceUpdate {
	if value != nil {
		return d.SetName(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdateOne) SetNotNilName(value *string) *DeviceUpdateOne {
	if value != nil {
		return d.SetName(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceCreate) SetNotNilName(value *string) *DeviceCreate {
	if value != nil {
		return d.SetName(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdate) SetNotNilDepartmentID(value *uint64) *DeviceUpdate {
	if value != nil {
		return d.SetDepartmentID(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdateOne) SetNotNilDepartmentID(value *uint64) *DeviceUpdateOne {
	if value != nil {
		return d.SetDepartmentID(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceCreate) SetNotNilDepartmentID(value *uint64) *DeviceCreate {
	if value != nil {
		return d.SetDepartmentID(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdate) SetNotNilHost(value *string) *DeviceUpdate {
	if value != nil {
		return d.SetHost(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdateOne) SetNotNilHost(value *string) *DeviceUpdateOne {
	if value != nil {
		return d.SetHost(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceCreate) SetNotNilHost(value *string) *DeviceCreate {
	if value != nil {
		return d.SetHost(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdate) SetNotNilDescription(value *string) *DeviceUpdate {
	if value != nil {
		return d.SetDescription(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceUpdateOne) SetNotNilDescription(value *string) *DeviceUpdateOne {
	if value != nil {
		return d.SetDescription(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (d *DeviceCreate) SetNotNilDescription(value *string) *DeviceCreate {
	if value != nil {
		return d.SetDescription(*value)
	}
	return d
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilUpdatedAt(value *time.Time) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetUpdatedAt(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilUpdatedAt(value *time.Time) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetUpdatedAt(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilUpdatedAt(value *time.Time) *PolicyAuthCreate {
	if value != nil {
		return pa.SetUpdatedAt(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilName(value *string) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetName(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilName(value *string) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetName(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilName(value *string) *PolicyAuthCreate {
	if value != nil {
		return pa.SetName(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilPower(value *int32) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetPower(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilPower(value *int32) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetPower(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilPower(value *int32) *PolicyAuthCreate {
	if value != nil {
		return pa.SetPower(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilDepartmentID(value *uint64) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetDepartmentID(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilDepartmentID(value *uint64) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetDepartmentID(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilDepartmentID(value *uint64) *PolicyAuthCreate {
	if value != nil {
		return pa.SetDepartmentID(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilUsers(value *string) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetUsers(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilUsers(value *string) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetUsers(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilUsers(value *string) *PolicyAuthCreate {
	if value != nil {
		return pa.SetUsers(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilAccounts(value *string) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetAccounts(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilAccounts(value *string) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetAccounts(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilAccounts(value *string) *PolicyAuthCreate {
	if value != nil {
		return pa.SetAccounts(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdate) SetNotNilDirection(value *bool) *PolicyAuthUpdate {
	if value != nil {
		return pa.SetDirection(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthUpdateOne) SetNotNilDirection(value *bool) *PolicyAuthUpdateOne {
	if value != nil {
		return pa.SetDirection(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (pa *PolicyAuthCreate) SetNotNilDirection(value *bool) *PolicyAuthCreate {
	if value != nil {
		return pa.SetDirection(*value)
	}
	return pa
}

// set field if value's pointer is not nil.
func (r *RoleUpdate) SetNotNilUpdatedAt(value *time.Time) *RoleUpdate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleUpdateOne) SetNotNilUpdatedAt(value *time.Time) *RoleUpdateOne {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleCreate) SetNotNilUpdatedAt(value *time.Time) *RoleCreate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleUpdate) SetNotNilName(value *string) *RoleUpdate {
	if value != nil {
		return r.SetName(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleUpdateOne) SetNotNilName(value *string) *RoleUpdateOne {
	if value != nil {
		return r.SetName(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleCreate) SetNotNilName(value *string) *RoleCreate {
	if value != nil {
		return r.SetName(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleUpdate) SetNotNilWeight(value *int) *RoleUpdate {
	if value != nil {
		return r.SetWeight(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleUpdateOne) SetNotNilWeight(value *int) *RoleUpdateOne {
	if value != nil {
		return r.SetWeight(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RoleCreate) SetNotNilWeight(value *int) *RoleCreate {
	if value != nil {
		return r.SetWeight(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilUpdatedAt(value *time.Time) *UserUpdate {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilUpdatedAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilUpdatedAt(value *time.Time) *UserCreate {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilAccount(value *string) *UserUpdate {
	if value != nil {
		return u.SetAccount(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilAccount(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetAccount(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilAccount(value *string) *UserCreate {
	if value != nil {
		return u.SetAccount(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilName(value *string) *UserUpdate {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilName(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilName(value *string) *UserCreate {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilPassword(value *string) *UserUpdate {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilPassword(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilPassword(value *string) *UserCreate {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilDepartmentID(value *uint64) *UserUpdate {
	if value != nil {
		return u.SetDepartmentID(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilDepartmentID(value *uint64) *UserUpdateOne {
	if value != nil {
		return u.SetDepartmentID(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilDepartmentID(value *uint64) *UserCreate {
	if value != nil {
		return u.SetDepartmentID(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilRoleID(value *uint64) *UserUpdate {
	if value != nil {
		return u.SetRoleID(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilRoleID(value *uint64) *UserUpdateOne {
	if value != nil {
		return u.SetRoleID(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilRoleID(value *uint64) *UserCreate {
	if value != nil {
		return u.SetRoleID(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilStatus(value *bool) *UserUpdate {
	if value != nil {
		return u.SetStatus(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilStatus(value *bool) *UserUpdateOne {
	if value != nil {
		return u.SetStatus(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilStatus(value *bool) *UserCreate {
	if value != nil {
		return u.SetStatus(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilDescription(value *string) *UserUpdate {
	if value != nil {
		return u.SetDescription(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilDescription(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetDescription(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilDescription(value *string) *UserCreate {
	if value != nil {
		return u.SetDescription(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilEmail(value *string) *UserUpdate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilEmail(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilEmail(value *string) *UserCreate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilPhoneNumber(value *string) *UserUpdate {
	if value != nil {
		return u.SetPhoneNumber(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilPhoneNumber(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetPhoneNumber(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilPhoneNumber(value *string) *UserCreate {
	if value != nil {
		return u.SetPhoneNumber(*value)
	}
	return u
}
