// Code generated by goctl. DO NOT EDIT.
package types

type UserDeleteRequest struct {
	UserIds []int `json:"user_ids"`
}

type UserVisibleInfo struct {
	UserId      int64  `json:"user_id" `     // 用户ID
	Account     string `json:"account"`     // 用户账号
	Username    string `json:"username"`    // 用户姓名
	DeptId      int64  `json:"dept_id"`     // 用户所属部门ID
	Disable     int64  `json:"disable"`     // 账号是否禁用
	Description string `json:"description"` // 账号描述
	CreateTime  string `json:"create_time"` // 创建时间
	RoleId      int64  `json:"role_id"`     // 用户角色ID
}

type UserAllInfo struct {
	UserVisibleInfo
	CreateByUid int64  `json:"create_by_uid"` // 创建人
	IsDelete    int64  `json:"is_delete"`     // 是否被删除
	Password    string `json:"password"`      // 用户密码
}

type UserVisibleInfoArray struct {
	Response
	Data []UserVisibleInfo `json:"data"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CommonResponse struct {
	Response
	Data string `json:"data"`
}

type AuthRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RoleDeleteRequest struct {
	RoleIds []int `json:"RoleIds"`
}

type RoleVisibleInfo struct {
	RoleId      int64  `json:"RoleId"`      // 角色ID
	Name        string `json:"name"`        // 角色名称
	Description string `json:"description"` // 角色描述
	CreateTime  string `json:"CreateTime"`  // 创建时间
}

type RoleAllInfo struct {
	RoleVisibleInfo
	CreateByUid int64 `json:"CreateByUid"` // 创建者
	IsDelete    int64 `json:"IsDelete"`    // 是否被删除
}

type RoleVisibleInfoArray struct {
	Response
	Data []RoleVisibleInfo `json:"data"`
}

type DeptDeleteRequest struct {
	DeptIds []int `json:"DeptIds"`
}

type DeptVisibleInfo struct {
	DeptId      int64  `json:"DeptId"`      // 部门ID
	Name        string `json:"name"`        // 部门名称
	Description string `json:"description"` // 部门描述
	ParentId    int64  `json:"ParentId"`    // 上级部门ID
	ChildIds    string `json:"ChildIds"`    // 下级部门ID集合，用逗号分隔
	Region      string `json:"region"`      // 部门所在地区
}

type DeptAllInfo struct {
	DeptVisibleInfo
	IsDelete    int64 `json:"IsDelete"`    // 是否被删除
	CreateByUid int64 `json:"CreateByUid"` // 创建者
}

type DeptVisibleInfoArray struct {
	Response
	Data []DeptVisibleInfo `json:"data"`
}


